### ISSUE TITLE
I can't get it to read the file continuously, putting each new line in the Topic

### ISSUE THREAD

**Issue by guilleGH** [streamthoughts/kafka-connect-file-pulse#105]
I have FilePulse correctly configured, so that when I create a file inside the reading folder, it reads it and ingests it in the topic.
Now I need to do continuous reading of each of the files in that folder, since they are continually being updated.
I have to change any property of properties file?

My filePulseTxtFile.properties:

name=connect-file-pulse-txt
connector.class=io.streamthoughts.kafka.connect.filepulse.source.FilePulseSourceConnector
topic=lineas-fichero
tasks.max=1

 #File types
fs.scan.filters=io.streamthoughts.kafka.connect.filepulse.scanner.local.filter.RegexFileListFilter
file.filter.regex.pattern=.*\\.log$
task.reader.class=io.streamthoughts.kafka.connect.filepulse.reader.RowFileInputReader

 #File scanning
fs.cleanup.policy.class=io.streamthoughts.kafka.connect.filepulse.clean.LogCleanupPolicy
fs.scanner.class=io.streamthoughts.kafka.connect.filepulse.scanner.local.LocalFSDirectoryWalker

fs.scan.directory.path=/home/ec2-user/parser/scanDirKafka
fs.scan.interval.ms=10000

 #Internal Reporting
internal.kafka.reporter.bootstrap.servers=localhost:9092
internal.kafka.reporter.id=connect-file-pulse-txt
internal.kafka.reporter.topic=connect-file-pulse-status

 #Track file by name
offset.strategy=name

Thanks a lot!

**Comment by fhussonnois** [comment]
Hi @guilleGH 

For doing continious reading you need to add this property `read.max.wait.ms` which is the maximum time (in milliseconds ) the `RowFileInputReader` will wait for more bytes after hitting end of file.

In addition, if new files are added to the input directory they will not be processed because tasks are still running for previous files. So, you can configure the `allow.tasks.reconfiguration.after.timeout.ms` to force all tasks to be restarted after a given period.

**Comment by guilleGH** [comment]
thank you very much, it works
