### ISSUE TITLE
Schedule new files while task is not completed.

### ISSUE THREAD

**Issue by Redanski** [streamthoughts/kafka-connect-file-pulse#195]
Hello i have the following current setup folder `files` which contains between 1-2 files.
New files might get created, if they get created they should be added to the currently processed files immediately.
Older files should be watched continuously or indefinitely because there will be new lines added to this file.

New files are only scheduled if the currently processed file has been marked as completed.
I naively assumed that increasing the tasks and putting `fs.listing.task.delegation.enabled` would allow me to do this, is that not the case?
Is there a way to change this behaviour?

Version 2.4.0
This is the config im running.
{
    "name": "raw",
    "config": {
      "connector.class": "io.streamthoughts.kafka.connect.filepulse.source.FilePulseSourceConnector",
      "fs.listing.class": "io.streamthoughts.kafka.connect.filepulse.fs.LocalFSDirectoryListing",
      "fs.cleanup.policy.class": "io.streamthoughts.kafka.connect.filepulse.fs.clean.LogCleanupPolicy",
      "fs.listing.directory.path": "/files",
      "fs.listing.filters": "io.streamthoughts.kafka.connect.filepulse.fs.filter.RegexFileListFilter",
      "fs.listing.interval.ms": "1000",
      "read.max.wait.ms": "60000",
      "file.filter.regex.pattern": ".*\\.log",
      "fs.listing.task.delegation.enabled" : true,
      "max.scheduled.files" : 1000,
      "topic": "raw",
      "tasks.reader.class":"io.streamthoughts.kafka.connect.filepulse.fs.reader.LocalRowFileInputReader",
      "tasks.file.status.storage.class": "io.streamthoughts.kafka.connect.filepulse.state.KafkaFileObjectStateBackingStore",
      "tasks.file.status.storage.bootstrap.servers": "broker:29092",
      "tasks.file.status.storage.topic": "connect-file-pulse-status",
      "tasks.file.status.storage.topic.partitions": 2,
      "tasks.file.status.storage.topic.replication.factor": 2,
      "tasks.max": 20
    }
  }

**Comment by fhussonnois** [comment]
Hi @Redanski, I'm not sure Connect FilePulse is the right solution if you have a constantly growing number of files to process. Because, a ConnectTask needs to complete a file before moving to the next one. So, you should always make sure that you have as many tasks as files to process...not sure this is suitable with the Kafka Connect architecture.

But if the files end up being considered complete at some point this should works.

The `read.max.wait.ms` property must be set to a value corresponding to the period during which a task must wait for more data to be written to the file before considering it complete. For example, if you set it to 1 hour, then if no data is written to the file for 1 hour, the file will be marked as completed and the task will start processing the next file assigned to it

In addition, the connector will never schedule new files while files are still being processed. The `allow.tasks.reconfiguration.after.timeout.ms` allows you to force a rescheduling when new files are detected after a given timeout.

**Comment by Redanski** [comment]
Hey thank you for your feedback.
Using the properties in your previous post, would work in theory.

But we ultimately moved to a different solution after consulting our internal IT Team, we will use their fluentbit with the respective kafka connector.
