### ISSUE TITLE
Json parse issue

### ISSUE THREAD

**Issue by Vladislaff** [streamthoughts/kafka-connect-file-pulse#202]
Hi,

I am having an issue when parsing json with arrays of arrays.
The data is lost after parsing.

Please see attached:
[payload_jsonl.txt](https://github.com/streamthoughts/kafka-connect-file-pulse/files/7635379/payload_jsonl.txt) - input file (4 lines. separate json object per line)
[messages_issue_test_1.txt](https://github.com/streamthoughts/kafka-connect-file-pulse/files/7635378/messages_issue_test_1.txt) - output message (1 of 4)
[connector_FilePulseConnectorJsonIssue_config.txt](https://github.com/streamthoughts/kafka-connect-file-pulse/files/7635380/connector_FilePulseConnectorJsonIssue_config.txt) - connector config

**Comment by fhussonnois** [comment]
Hi @Vladislaff, I will try to reproduce your issue. For now, everything seems to be working while parsing local file. Here is the schema generated by the connector : [schema.json.txt](https://github.com/streamthoughts/kafka-connect-file-pulse/files/7654028/schema.json.txt)...I will do further investigations.

**Comment by Vladislaff** [comment]
Hi, I am using 2.4.0 from Confluent Hub.
Sending rows directly into Kafka via a producer works (without this connector).

The attached generated schema does not seem to be correct. 
VAL3 is lost, COL2 through COL8 in the embedded GRID are also lost.
If I use an online tool to generate the schema (for example, https://toolslick.com/generation/metadata/avro-schema-from-json) it gives me a completely different result.

**Comment by fhussonnois** [comment]
Hi @Vladislaff, ok I got it! Unfortunatly, Kafka Connect does not support UNION with multiple types, so this is a limitation of the framework not FilePulse. 

However, some columns are lost because FilePulse only uses the first record of an Array to infer the value-schema. I could provide a fix for by merging all fields from all records in the array but this will not solve the problem because in your case the `data` arrays may contain both `string` and `number` values (see: https://issues.apache.org/jira/browse/KAFKA-10625, https://github.com/confluentinc/ksql/issues/1910)

So, I suggest to you to not parse the JSON lines with FilePulse but to directly send each raw line directly into Kafka and to use another service (e.g. Kafka Streams to parse JSON rows).

**Comment by Vladislaff** [comment]
Hi, Thank you.
How can I send the raw line without parsing?
As I understand the ByteArray reader reads in the full file. How can I use the Row reader to read strings (or bytearrays)?

**Comment by fhussonnois** [comment]
Hi @Vladislaff, don't use the `JSONFilter` so you will have one record per line containing a field `message` with the raw JSON. Then, you should be able to use the [`AppendFilter`](https://streamthoughts.github.io/kafka-connect-file-pulse/docs/developer-guide/filters/#appendfilter) to move that field to the top level

**Comment by Vladislaff** [comment]
Hi @fhussonnois,
What do I need to put as field to move the value to the top?
<pre>filters.SubstituteFilter.type: io.streamthoughts.kafka.connect.filepulse.filter.AppendFilter
filters.SubstituteFilter.field: <b><i>"$."</i></b>
filters.SubstituteFilter.value: "{{ $.message }}"
</pre>

**Comment by fhussonnois** [comment]
Hi @fhussonnois, try this one : 

```
filters.SubstituteFilter.type: io.streamthoughts.kafka.connect.filepulse.filter.AppendFilter
filters.SubstituteFilter.field: "$value"
filters.SubstituteFilter.value: "{{ $value.message }}"
```
