### ISSUE TITLE
log4j vulnerability 

### ISSUE THREAD

**Issue by mohai-kafka** [streamthoughts/kafka-connect-file-pulse#213]
Team,

We are using 2.4.0 version and my security team identified 2.4.0 is using log4j-1.2.17.jar and JMSAppender class. Is Log4J "Log4Shell" Zero-Day Vulnerability effected this version?

**Comment by slachiewicz** [comment]
See here: https://logging.apache.org/log4j/2.x/

**Comment by fhussonnois** [comment]
Hi @mohai-kafka,

FilePulse depends on Kafka and Kafka Connect librariries which use log4j 1.2.17.jar. which is not direcly affected by the CVE. You can refer to this official documentation:  https://kafka.apache.org/cve-list

If you install FilePulse from zip distribution (or confluent-hub) you can remove the JMSAppender using the commands described in https://www.slf4j.org/log4shell.html

**Comment by mohai-kafka** [comment]
@fhussonnois thanks. One basic question is we are using lot of other Confluent connectors and they also yawing same log4j version. When my security team scan all the directory it is not found JMSAppender class in any other log4j folder except file pulse lib folder. Question is 

mother connectors removed JMSAppender.class when they package the zip?

**Comment by fhussonnois** [comment]
The Connect FilePulse /lib directory do contains the log4J-1.2.17.jar that contains the JMSAppender. 
But for example, the confluent-jdbc-connector doesn't directly contains this JAR. which is in any case already provided by Kafka Connect (workers).

So I think this is due to a bad configuration of the maven project dependencies. 
It should be safe to remove the log4j jar from the connect-file-pulse directory as it is already present in the Kafka Connect's classpath.
