### ISSUE TITLE
Is there a way to identify when the last row of a CSV file is consumed?

### ISSUE THREAD

**Issue by serioja** [streamthoughts/kafka-connect-file-pulse#216]
In some case I want to wait to have all the rows of the files to run some action (for example build a dataframe using the full CSV).
I tried to use the internal.kafka.reporter.topic but I can get a COMPLETED status before receiving the last row.

**Comment by fhussonnois** [comment]
Hi @serioja,

Since Connect FilePulse 2.4.x, using the internal `connect-file-pulse-status` topic, you have a `COMMITTED` status which gives you the guarantee that all data in a file has been produced in Kafka.

Another solution could be to inject file offset metadata as Kafka record-headers, see https://streamthoughts.github.io/kafka-connect-file-pulse/docs/developer-guide/accessing-data-and-metadata/#record-offset

Using the `$offset.endPosition` and `$metadata.size`  should also help you. Basically, if $offset.endPositiion >= $metadata.size then record is the last one.

You can use the `AppendFilter` to add `$offset.endPosition` to the record-header.

**Comment by serioja** [comment]
Thank you for your quick answer. I will try these approaches.  For the first one, I have a doubt though: I may have COMMITTED but I will still receive some data after receiving the COMMITED event. I may be wrong, but I think I have observed this behaviour. 
The second one should fit exactly my needs.
