### ISSUE TITLE
How to retry when a file processing gets into FAILED status

### ISSUE THREAD

**Issue by shashank-ovo** [streamthoughts/kafka-connect-file-pulse#255]
We are trying out the connector (version 2.4.3) to read a csv file from the GCS bucket. 
The files goes through the following statuses :
- Scheduled
- Started
- Failed
- Cleaned
In our case the failure was due to AppendFilter. 

Is there a way to retry the failed files? I am using `name+lastmodified` as offset strategy, however, I've to re-upload the file every time to trigger the processing again. 

Below is the configuration I am using.

```
{
  "name": "FilePulse_KafkaNonProd_TestdbV1",
  "connector.class": "io.streamthoughts.kafka.connect.filepulse.source.FilePulseSourceConnector",
  "filters": "ParseDelimitedRow, SetKey, AppendFilter",
  "filters.ParseDelimitedRow.separator": ",",
  "filters.ParseDelimitedRow.trimColumn": "true",
  "filters.ParseDelimitedRow.extractColumnName": "headers",
  "filters.ParseDelimitedRow.type": "io.streamthoughts.kafka.connect.filepulse.filter.DelimitedRowFilter",
  "filters.SetKey.type": "io.streamthoughts.kafka.connect.filepulse.filter.AppendFilter",
  "filters.SetKey.field": "$key",
  "filters.SetKey.value": "$value.pkField",
  "filters.AppendFilter.type": "io.streamthoughts.kafka.connect.filepulse.filter.AppendFilter",
  "filters.AppendFilter.field": "$.fileMetadata.name",
  "filters.AppendFilter.value": "$metadata.name",
  "filters.AppendFilter.field": "$.fileMetadata.lastModified",
  "filters.AppendFilter.value": "$metadata.lastModified",
  "filters.AppendFilter.field": "$.fileMetadata.path",
  "filters.AppendFilter.value": "$metadata.path",
  "fs.cleanup.policy.class": "io.streamthoughts.kafka.connect.filepulse.fs.clean.LogCleanupPolicy",
  "fs.listing.class": "io.streamthoughts.kafka.connect.filepulse.fs.GcsFileSystemListing",
  "fs.listing.interval.ms": "10000",
  "gcs.bucket.name":"test-filepulseconnector",
  "offset.attributes.string": "name+lastModified",
  "skip.headers": "1",
  "topic": "Test_FilePulseConnector_v1",
  "tasks.max": 1,
  "tasks.reader.class": "io.streamthoughts.kafka.connect.filepulse.fs.reader.GcsRowFileInputReader",
  "tasks.file.status.storage.bootstrap.servers": "",
  "tasks.file.status.storage.class": "io.streamthoughts.kafka.connect.filepulse.state.KafkaFileObjectStateBackingStore",
  "tasks.file.status.storage.topic": "test_filePulseConnector_status"
}
```

**Comment by shashank-ovo** [comment]
Hi,

Can anyone help me out with this? I do not see any option to re-schedule the failed files.

**Comment by fhussonnois** [comment]
Hi @shashank-ovo, currently FilePulse does not provide any built-in mecanism for retrying failed file. Once a file is marked as COMPLETED, COMITTED or FAILED it is handled by the configured cleanup.policy and then marked CLEANED so that it will be ignored by the connector listing process.

A first solution would be to implement your own `FileCleanupPolicy`, for example, to rename your file with a specific prefix OR suffix such as `RETRY-ATTEMPT-1` so that it will be considered by the connector as a new file. Otherwise,  you could also remove the entry that correspond to your file in the `test_filePulseConnector_status` by sending a `null` record-value for the attached key.
