### ISSUE TITLE
Can we create directory walker for S3 and fetch files from there ?

### ISSUE THREAD

**Issue by akhileshacc** [streamthoughts/kafka-connect-file-pulse#41]
Hi, 

i have been using file pulse on local system to read csv, json and pdf files.
Now, i am trying to read files from S3. 
Is there a way to read files from there, by creating custom folder walker.

**Comment by fhussonnois** [comment]
Hi @akhileshacc, well I don't know if that currently possible because you will have to implement the `FSDirectoryWalker` interface to list objects on S3 bucket. However the  `FSDirectoryWalker` interface should return a list of `File` and with S3 it would be suitable to return a list of `URI`.

In addition, you will have to implement a custom `FileInputReader`.

So I think it would be necessary to make some changes in the File Pulse API.

**Comment by fhussonnois** [comment]
see: https://github.com/streamthoughts/kafka-connect-file-pulse/issues/111
