### ISSUE TITLE
Not able to get "timestamp"

### ISSUE THREAD

**Issue by akhileshacc** [streamthoughts/kafka-connect-file-pulse#45]
Hi, 

i am using filepulse to read text files using following config. I want to add timestamp using Kafka transform.

```
name=TextSourceConnector
connector.class=io.streamthoughts.kafka.connect.filepulse.source.FilePulseSourceConnector
topic=text-source
tasks.max=1
transforms=InsertField
transforms.InsertField.timestamp.field=loadedAt
transforms.InsertField.type=org.apache.kafka.connect.transforms.InsertField$Value
task.reader.class=com.accern.reader.TextFileInputReader
fs.cleanup.policy.class=io.streamthoughts.kafka.connect.filepulse.clean.LogCleanupPolicy
fs.scanner.class=io.streamthoughts.kafka.connect.filepulse.scanner.local.LocalFSDirectoryWalker
fs.scan.directory.path=/tmp/data/text
fs.scan.interval.ms=10000
internal.kafka.reporter.bootstrap.servers=localhost:9092
internal.kafka.reporter.id=filepulse-text
internal.kafka.reporter.topic=filepulse-status
offset.strategy=name+hash
```

I get output like this
```
{
"message":"Some message",
"title":"my title",
"loadedAt":null
}
```

I tried searching, They say, We need to add "timestamp" to kafka's SourceRecord at time of creating it. How do i do that with filepulse ?

**Comment by akhileshacc** [comment]
I am using a custom reader

**Comment by fhussonnois** [comment]
Hi @akhileshacc, I'm nore sure this problem is related to Connect File Pulse. As I understand it, you would like to inject a field `loadedAt` with the record timestamp but at the end the field is still `null`. According to this [issue] this is due because the record.timestamp is not set by the connector.

If you are using a custom reader, then I suggest to you to return a `TypedFileRecord` or at-least to make sure that `SourceRecord` you build from your FileRecord set the timestamp.

**Comment by fhussonnois** [comment]
Hi @akhileshacc, could you please close this issue if your problem is resolved. Thanks.
