### ISSUE TITLE
XML ingestion - map xml elements to apache avro classes

### ISSUE THREAD

**Issue by hirsche** [streamthoughts/kafka-connect-file-pulse#49]
Hi,

I am ingesting XML files and writing them to a kafka topics. According to documentation, I am matching elements (including sub-elements) using an xpath query.

I'd like to know if it would it be possible to map the resulting entities (elements) together with their properties (sub-elements or element attributes) to avro-classes (taken from kafka schema-registry) which already exist and thus use pre-defined data types. Otherwise, most (maybe all?) of the automatically created schema fields are defined using String data types.

Many Thank for your help,
Eduard

**Comment by fhussonnois** [comment]
Hi @hirsche, to be honest the [`XMLFileInputReader`](https://github.com/streamthoughts/kafka-connect-file-pulse/blob/master/connect-file-pulse-plugin/src/main/java/io/streamthoughts/kafka/connect/filepulse/reader/XMLFileInputReader.java) is not very evolved and does very basic stuff. It try to dynamically infer a data structure by iterating over the document nodes.

So unfortunately, the answer is no. You cannot match a schema that exists in the SchemaResgistry with an input XML Document.
But, if your need is to convert field into another type then may you can use the [ConvertFilter](https://streamthoughts.github.io/kafka-connect-file-pulse/docs/developer-guide/filters/#convertfilter). Otherwise, you can implement/extend your own `XMLFileInputReader`

**Comment by hirsche** [comment]
Ok, thx - the ConverFilter will do the trick ... at least for me ;)
