### ISSUE TITLE
Unable to write record metadata to the row dynamically

### ISSUE THREAD

**Issue by Ram-Kotamraju** [streamthoughts/kafka-connect-file-pulse#70]
Hi, I am trying to use File Pulse (1.3.1) for reading a csv file and 

- insert a field using AppendFIlter for each record.
- And add a value to the field as 'Rownumber' of 'Total Recs' (1/25, 2/25, 3/25 etc...)
- Tried various filters without success. 
Any thoughts about achieving this?
```
# The type of the filter
filters.RowinBatch.type=io.streamthoughts.kafka.connect.filepulse.filter.AppendFilter
# The name of the field to add
filters.RowinBatch.field=RowinBatch
filters.RowinBatch.values="{{ $offset.row}}"
```

Tried various other filters also like transform.
```
transforms=InsertSource
transforms.InsertSource.type=org.apache.kafka.connect.transforms.InsertField$Value
transforms.InsertSource.static.field=RinB
transforms.InsertSource.static.value="{{ $offset.row}}"
```
Thanks
Ram

**Comment by fhussonnois** [comment]
Hi @Ram-Kotamraju, fist could you update to the latest version 1.5.1 or at least to the 1.5.0 which is available on Confluent-Hub : https://www.confluent.io/hub/streamthoughts/kafka-connect-file-pulse

FilePulse's filters and Connect's Transform are two distinct mecanism that can be used together but Transformer does not support expression like `{{ $offset.row}}`.

Unfortunately, you cannot insert total-records because this information is unknown. 

The following configuration will insert a field `row` containing the row number of the record in the source file.
```
filters=AppendRowNumber
filters.AppendRowNumber.type=io.streamthoughts.kafka.connect.filepulse.filter.AppendFilter
# The name of the field to add
filters.AppendRowNumber.field=row
filters.AppendRowNumber.value={{ $offset.row }}

**Comment by Ram-Kotamraju** [comment]
Thanks for the quick reply @fhussonnois ... I will give it a shot and let you know.
